version: '2.3'

services:  
  db:
    image: postgres
    volumes:      
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ruby-postgres
    environment:
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
  webapp:    
    build:      
      context: ../../webapp
      dockerfile: Dockerfile.dev
    volumes:
      - data01:/box
      - ../../webapp:/var/www/app/webapp/
    links:
      - db
    networks:
      - ruby-postgres
  box:
    image: busybox
    volumes:
      - data01:/box
  nginx:
    build:      
      context: ../../nginx    
      dockerfile: Dockerfile  
    ports:      
      - 80:80
    networks:
      - ruby-postgres
    links:
      - webapp
volumes:  
  postgres_data: {} 
  data01:
    driver: local
  
networks:
  ruby-postgres:
    driver: bridge
